import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { calistoga, merriweather, poppins } from "./fonts";
import NavbarProvider from "./NavbarProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
      // className={`${calistoga.classname} ${merriweather.classname} ${poppins.classname} `}
      >
        <Providers>
          <NavbarProvider />
          {children}
        </Providers>
      </body>
    </html>
  );
}
