import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { calistoga } from "./fonts";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={calistoga.className}>
        <Providers>
            <Navbar/>
            {children}
        </Providers>
      </body>
    </html>
  );
}
